### ISSUE TITLE
iPad mini 2下載相片會遺失

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-bank#5] opened 2014-08-21 06:10 UTC
Enduser使用Air Bank下載相片到iPad，下載完成後iPad卻找不到那相片。
請問會是什麼原因? 因Enduser在他的Android平板跟iPad第一代是沒這個問題發生。
系統資訊：
iPad mini 2 (配備Retina顯示器)
iPad 運行OS版本 7.1.2

**Comment by yiming330** [comment] 2014-09-03 16:37
The issue is under investigation.

**Comment by yiming330** [comment] 2014-09-11 16:11
We have done the research and confirmed that this is not a functional issue. It's a user operation issue.
Below attached the screenshots of sucessful downloading image files from AirBank to iPad Mini.
![1](https://cloud.githubusercontent.com/assets/5311668/4237375/44cbc654-39ce-11e4-9ea1-5224a0bf7ed0.PNG)
![2](https://cloud.githubusercontent.com/assets/5311668/4237379/44d2f794-39ce-11e4-83ba-862d2c78d34c.PNG)
![3](https://cloud.githubusercontent.com/assets/5311668/4237376/44d026ae-39ce-11e4-9664-4416fc91aae8.PNG)
![4](https://cloud.githubusercontent.com/assets/5311668/4237378/44d25cc6-39ce-11e4-8b33-fe161d20ff07.PNG)
![5](https://cloud.githubusercontent.com/assets/5311668/4237380/44d6231a-39ce-11e4-801e-d7348f19dd25.PNG)
![6](https://cloud.githubusercontent.com/assets/5311668/4237377/44d21e32-39ce-11e4-904b-d8c5334ec6ef.PNG)

**Comment by yiming330** [comment] 2014-09-11 16:25
The user might have rejected the access request to iOS Photo Album when they first installed the AirBank+ app.
Please advice end user to do the following setting, and try performing the operation again.
1. Select "Settings"
2. Select "Privacy
3. Select "Photos"
4. Make sure the PQI AirBank+ has been turned on for photo access.
   ![img_5125](https://cloud.githubusercontent.com/assets/5311668/4237570/3fdffabe-39d0-11e4-99e0-309d35f92d0e.PNG)

**Comment by yiming330** [comment] 2014-10-21 02:02
As above explanations, this has been verified, and confirmed that it's not a bug. Closing the issue for now.

**Closed as completed by yiming330** 2014-10-21 02:02 UTC
Labels: wontfix, Investigation
