### ISSUE TITLE
Air Bank 的APP 在ipad Air上無法播放

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-bank#4] opened 2014-08-08 03:10 UTC
PQI Air Bank+ app is not working at Ipad air.
It is working well on Iphone 4s, but doesn't work on my ipad air.
Let me know how can I open movies on my ipad?

**Comment by yiming330** [comment] 2014-08-08 03:58
請提供錯誤的情形, (例如: 無法開啟app, 或是閃退, 或是某個功能無法使用). 如果可以的話, 也請提供screenshot, 還有iOS的版本.

**Comment by yiming330** [comment] 2014-09-03 16:43
Unable to reproduce the issue. The issue is closing for now.

**Closed as completed by yiming330** 2014-09-03 16:43 UTC
Labels: Investigation
