### ISSUE TITLE
Air Bank 影片檔是否可以放播放smi字幕檔

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-bank#6] opened 2014-08-21 06:13 UTC
Customer ask how to see “smi” Korean subtitle when watching movie via Airbank APP.

**Comment by yiming330** [comment] 2014-09-03 16:36
First, we need to know whether the customer is using iOS device or Android device. 
On iOS, It's not a supported function either on the system or the app.
On Android, the customer will be able to open media files from any of the installed media player on the device. So it really depends on whether the 3rd party media player supports subtitle playback or not.

**Comment by yiming330** [comment] 2014-10-21 02:04
As above explanations, this has been verified, and confirmed that it's not a bug. Closing the issue for now. However, the iOS app can be improved if a new Change Request approved to develop independent media player, which can play a lot of more media formats than then iOS built-in player.

**Closed as completed by yiming330** 2014-10-21 02:04 UTC
Labels: question, wontfix
