### ISSUE TITLE
Air BAnk 在NTFS格式下4G檔案無法播放

### ISSUE THREAD

**Issue by PQI-APP** [yiming330/pqi-air-bank#10] opened 2014-10-20 08:29 UTC
Now, the file has already stored in PQI Air Bank. Of course, the Air Bank is formatted as NTFS.
Then the customer tried to play the file on his smart phone, but it can’t be played.

The codec and file format is not a problem because the file can be played if its file size is decreased to under 4GB.
- Our staff just cut its last a few minutes.

So we doubt its file size is the cause of this matter.

**Comment by yiming330** [comment] 2014-10-20 15:16
Does it only happen on iOS app or Android? Or both? What is the file format? (.mp4?)

**Comment by PQI-APP** [comment] 2014-10-21 01:10
My answer is as the following.
1. We tested both of iOS and Android.
      Android version is 4.4.2 and 4.1.2 .
      iOS version is 8.0.1.
 App version is the newest on iOS and Android.
 The test results are just same. We can’t play the movie.
1. File format is .mp4.

**Comment by yiming330** [comment] 2014-10-21 09:54
According to iOS File System (HFSX) spec, the system cannot take files more than 4gb.
http://en.wikipedia.org/wiki/HFS_Plus

![ios](https://cloud.githubusercontent.com/assets/5311668/4716425/39f013c6-5908-11e4-9afc-7ab746f47815.png)

**Comment by PQI-APP** [comment] 2014-10-21 09:59
Android system has 4gb limitation?

**Comment by yiming330** [comment] 2014-10-24 02:28
目前看來, Android官方的文件, 也顯示無法存取4GB以上的資料
https://www.android.com/filetransfer/
![android](https://cloud.githubusercontent.com/assets/5311668/4764441/61841756-5b25-11e4-9193-acb7776a8c39.png)

**Comment by PQI-APP** [comment] 2014-10-24 02:31
For IOS system, PQI JP branch feedback as below:
I think the point you indicate shows the limitation of file numbers.
And the picture shows that Max. file size is 8 exabyte.
It is enough large to manage the file which has over 4GB.
It might not its root cause.

**Comment by yiming330** [comment] 2014-10-24 02:38
We will do some more test to track down the root causes.

**Comment by yiming330** [comment] 2015-06-24 07:58
Closing the issue.
1. The files are accessed by URL provided by the web service running on the Linux on Airbank. 
2. The Linux is unable to handle the file over 4gb.
3. To fix the issue, will require firmware changes from hardware vendor.

**Closed as completed by yiming330** 2015-06-24 07:58 UTC
Labels: Investigation
